# Use root/example as user/password credentials
version: '3.1'

services:
  mongodb:
    image: mongo:4.0.8
    container_name: mongodb
    restart: unless-stopped
    command: mongod --auth
    volumes:
      - ./mongo/data:/data/db
    ports:
      - "27017:27017"